# -*- coding: utf-8 -*-
"""[NRC_8393]_PROYECTO_ToapantaMartinez_JonathanElian_CANTONES.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otn-dxhBVMJln9uWerhmgxJl9Mnug4eu
"""

'''Primero importamos todas las librerias 
que vamos a utilizar'''

!pip install faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

#Numero de datos a obtener
num_users = 5000

# Generar 4 atributos de la entidad 

features = [
    "Id_Canton",
    "Nombre_c",
    "Status_c",
    "Id_Coor"
]# Se crea un df para estos atributos
df = pd.DataFrame(columns=features)

"""# ID_Canton"""

'''Mediante la libreria uuid se implementa un ID a los Cantones, 
el cual va a ser único para cada dato'''

df['Id_Canton'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['Id_Canton'].nunique()==num_users)

"""# Nombre_Canton"""

'''Se creo un arrelgo que poseea los cantones de la provincia de Pichincha. 
Con ayuda de random.choices se asigno un procentaje para cada canton.
Esto determina en numero de veces que aparece cada uno. Aquí se le asigno mayor probabilidad al canton del Distrito Metropolitano de Quito 
puesto que, es la zona donde vamos a desarrollar el proyecto'''

canton = ["Cayambe","Distrito Metropolitano de Quito","Mejia","Pedro Moncayo", "Pedro Vicente Maldonado","Puerto Quito","Rumiñahui","San Miguel de los Bancos"]
df['Nombre_c'] = random.choices(
    canton, 
    weights=(5,65,5,5,5,5,5,5), 
    k=num_users
)

"""# Status Canton"""

#Se asgino un estatus mediante un dato categorico demostrarndo si la provincia esta vigente o no existe
#Con ayuda de random.choices de establecio el estatus
estadoC = ["En vigencia", "No existe"]
df['Status_c'] = random.choices(
    estadoC, 
    weights=(97,3), 
    k=num_users
)

"""# Id_coordenadas"""

'''Mediante la libreria uuid se implementa un ID a Coordenadas, 
el cual va a ser único para cada dato'''

df['Id_Coor'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['Id_Coor'].nunique()==num_users)

"""# Resultados"""

#Creacion del dataset
df.to_csv('dataset_Canton.csv')

#Visualizacion del dataset
pd.read_csv('dataset_Canton.csv', index_col=0)