# -*- coding: utf-8 -*-
"""[NRC_8393]_PROYECTO_ToapantaMartinez_JonathanElian_PROVINCIAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M7R_2eITf9nbvjJrZ9PFJfknFXgU7oFD
"""

'''Primero importamos todas las librerias 
que vamos a utilizar'''
!pip install faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

#Numero de datos a obtener
num_users = 5000

# Generar 4 atributos de la entidad Provincias
features = [
    "idProv",
    "Nombre_Pr",
    "Status_Pr"
    "Id_Coor"
]# Se crea un df para estos atributos
df = pd.DataFrame(columns=features)

"""# IdProvincia

"""

'''Mediante la libreria uuid se implementa un ID a las provincias, 
el cual va a ser unico para cada dato obtenido'''

df['idProv'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['idProv'].nunique()==num_users)

"""# Nombre_Pr"""

'''Se creo un arrelgo que poseea las 24 provincicias de Ecuador. 
Con ayuda de random.choices se asigno un procentaje para cada provincia.
Esto determina en numero de veces que apare cada una. Aquí se le asigno mayor probabilidad a la provincia de pichincha 
puesto que, es la zona donde vamos a desarrollar el proyecto'''

Provincias = ["Esmeraldas","Manabí","Los Ríos","Santa Elena","Guayas","Santo Domingo de los Tsáchilas","El Oro","Azuay",
              "Bolívar","Cañar","Carchi","Cotopaxi","Chimborazo","Imbabura","Loja","Pichincha","Tungurahua", "Morona Santiago",
              "Napo","Orellana","Pastaza","Sucumbíos","Zamora Chinchipe","Galapagos"]

df['Nombre_Pr'] = random.choices(
    Provincias, 
    weights=(3,3,3,3,4,3,3,4,3,4,4,4,3,3,3,20,4,4,4,4,4,4,3,3), 
    k=num_users
)



"""# Status_Pr"""

#Se asgino un estatus mediante un dato categorico demostrarndo si la provincia esta vigente o no existe
Estado = ["En vigencia", "No existe"]

#Con ayuda de random.choices de establecio el estatus
df['Status_Pr'] = random.choices(
    Estado, 
    weights=(97,3), 
    k=num_users
)

"""# IdCoor"""

'''Mediante la libreria uuid se implementa un ID a Coordenadas, 
el cual va a ser único para cada dato'''

df['Id_Coor'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['Id_Coor'].nunique()==num_users)

"""# Resultados"""

#Creacion del dataset
df.to_csv('dataset_Prov.csv')

df.drop(columns=["Status_PrId_Coor"])

#Visualizacion del dataset
pd.read_csv('dataset_Prov.csv', index_col=0)