# -*- coding: utf-8 -*-
"""[NRC_8393]_PROYECTO_ToapantaMartinez_JonathanElian_PARROQUIAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13OeMcVvz8tuPrV0Sq7qZROsx4LSHnFaK
"""

'''Primero importamos todas las librerias 
que vamos a utilizar'''

!pip install faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

#Numero de datos a obtener

num_users = 5000

# Generar 6 atributos de la entidad Coordenandas
features = [
    "Id_Parr",
    "Nombre_Prq",
    "Status_Prq",
    "idProv",
    "Id_Canton",
    "Id_Coor"
]# Se crea un df para estos atributos
df = pd.DataFrame(columns=features)

"""# ID_Parroquia"""

'''Mediante la libreria uuid se implementa un ID a las parroquias, 
el cual va a ser unico para cada dato'''

df['Id_Parr'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['Id_Parr'].nunique()==num_users)

"""# Nombre Parroquia"""

'''Se creo un arrelgo que poseea las parroquias. 
Con ayuda de random.choices se asigno un procentaje para cada parroquia.
Esto determina en numero de veces que aparece cada uno. Aquí se le asigno mayor probabilidad de la parroquia 
puesto que, es la zona donde vamos a desarrollar el proyecto'''

parroq = ["Belisario Quevedo","Carcelén","Centro Histórico","Chilibulo","Chillogallo","Chimbacalle","Cochapamba","Comité Pueblo",
          "Concepción","Cotocollao", "El Condado","El Inca","Guamaní","Iñaquito","Itchimbía","Jipijapa","Kennedy",
          "La Argelia","La Ecuatoriana","La Ferroviaria","La Libertad","La Mena","Magdalena","Mariscal Sucre","Ponceano","Puengasí",
          "Quitumbe","Rumipamba","San Bartolo","San Juan",'Solanda',"Turubamba"
]
df['Nombre_Prq'] = random.choices(
    parroq, 
    weights=(1,1,40,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,30,1,1,1,1,1,1,1,1,1,1,1), 
    k=num_users
)

"""# Status"""

#Se asgino un estatus mediante un dato categorico demostrarndo si la provincia esta vigente o no existe
#Con ayuda de random.choices de establecio el estatus
Estado = ["En vigencia", "No existe"]
df['Status_Prq'] = random.choices(
    Estado, 
    weights=(98,2), 
    k=num_users
)

"""# Id Provincia"""

'''Mediante la libreria uuid se implementa un ID a las provincias, 
el cual va a ser único para cada dato obtenido'''

df['idProv'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['idProv'].nunique()==num_users)

"""# Id Canton

"""

'''Mediante la libreria uuid se implementa un ID del Canton, 
el cual va a ser único para cada dato obtenido'''

df['Id_Canton'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['Id_Canton'].nunique()==num_users)

"""# Id Coordenadas"""

'''Mediante la libreria uuid se implementa un ID a Coordenadas, 
el cual va a ser único para cada dato'''

df['Id_Coor'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['Id_Coor'].nunique()==num_users)

"""# Resultados"""

#Creacion del dataset
df.to_csv('dataset_parroquia.csv')

#Visualizacion del dataset
pd.read_csv('dataset_parroquia.csv', index_col=0)