# -*- coding: utf-8 -*-
"""[NRC_8393]_PROYECTO_ToapantaMartinez_JonathanElian_BARRIOS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MeQeCtnHVZOFnlKvnOHkyNhuVGd3v7Fq
"""

'''Primero importamos todas las librerias 
que vamos a utilizar'''

!pip install faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

num_users=5000

# Generar 5 atributos de la entidad Coordenandas
features = [
    "IdBarrio",
    "Nombre_Barrio",    
    "IdCiu",
    "Id_Coor",
    "IdUPC"
]# Se crea un df para estos atributos
df = pd.DataFrame(columns=features)

"""# Id Barrio """

'''Mediante la libreria uuid se implementa un ID al Barrio, 
el cual va a ser unico para cada dato'''

df['IdBarrio'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['IdBarrio'].nunique()==num_users)

"""# Nombre Barrio   
   
"""

'''Se creo un arrelgo que poseea los Barrios. 
Con ayuda de random.choices se asigno un procentaje para cada barrio de la ciudad de la provincia de pichincha.
Esto determina en numero de veces que aparece cada uno. Aquí se le asigno mayor probabilidad de los Barrios 
puesto que, es la zona donde vamos a desarrollar el proyecto'''

barrio = ["Carcelén","El Condado","Cotocollao","Ponceano","Comité del Pueblo","Kennedy","Cochapamba","La Concepción","Jipijapa","Iñaquito","Rumipamba","Belisario Quevedo",
"Mariscal Sucre","San Juan","Centro Histórico","La Libertad","Itchimbía","Puengasí","La Magdalena","Chimbacalle","San Bartolo","Chilibulo","La Ferroviaria","La Argelia",
"La Mena","Solanda","Chillogallo","Quitumbe","La Ecuatoriana","Guamaní","Turubamba","Calderón","San Roque","San Diego"
]
df['Nombre_Barrio'] = random.choices(
    barrio, 
    weights=(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,8,60), 
    k=num_users
)

"""# Id Ciudad"""

'''Mediante la libreria uuid se implementa un ID a las ciudades, 
el cual va a ser único para cada dato obtenido'''

df['IdCiu'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['IdCiu'].nunique()==num_users)

"""# Id Coordenada
   
"""

'''Mediante la libreria uuid se implementa un ID a Coordenadas, 
el cual va a ser unico para cada dato'''

df['Id_Coor'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['Id_Coor'].nunique()==num_users)

"""# Id UPC"""

'''Mediante la libreria uuid se implementa un ID de la UPC, 
el cual va a ser único para cada dato obtenido'''

df['IdUPC'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['IdUPC'].nunique()==num_users)

"""# Resultados"""

#Creacion del dataset
df.to_csv('dataset_BARRIO.csv')

#Visualizacion del dataset
pd.read_csv('dataset_BARRIO.csv', index_col=0)