# -*- coding: utf-8 -*-
"""[NRC_8393]_PROYECTO_ToapantaMartinez_JonathanElian_CIUDAD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IilZS9lX7RQHCJERTXwhjsgJTXq2HCjQ
"""

'''Primero importamos todas las librerias 
que vamos a utilizar'''

!pip install faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

#Numero de datos a obtener
num_users=5000

# Generar 4 atributos de la entidad Coordenandas

features = [
    "IdCiu",
    "Nombre_Ciu",
    "Status_Ciu",
    "idProv",
    "Id_Canton",
    "Id_Coor"
]# Se crea un df para estos atributos
df = pd.DataFrame(columns=features)

"""#  Id Ciudad

"""

'''Mediante la libreria uuid se implementa un ID a las ciudades, 
el cual va a ser único para cada dato obtenido'''

df['IdCiu'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['IdCiu'].nunique()==num_users)

"""#   Nombre_Ciudad
   
"""

'''Se creo un arrelgo que poseea las cuidades. 
Con ayuda de random.choices se asigno un procentaje para cada ciudad de la provincia de pichincha.
Esto determina en numero de veces que aparece cada uno. Aquí se le asigno mayor probabilidad de las cuidades 
puesto que, es la zona donde vamos a desarrollar el proyecto'''

ciudad = ["Aloag","Cayambe","Machachi","Quito","San Miguel De Los Bancos","Sangolquí","Tabacundo"
]
df['Nombre_Ciu'] = random.choices(
    ciudad, 
    weights=(5,5,5,70,5,5,5), 
    k=num_users
)

"""# Estatus_Ciudad
    
"""

#Se asgino un estatus mediante un dato categorico demostrarndo si la provincia esta vigente o no existe
#Con ayuda de random.choices de establecio el estatus
Estado = ["En vigencia", "No existe"]
df['Status_Ciu'] = random.choices(
    Estado, 
    weights=(98,2), 
    k=num_users
)

"""# Id Provincia"""

'''Mediante la libreria uuid se implementa un ID a las provincias, 
el cual va a ser único para cada dato obtenido'''

df['idProv'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['idProv'].nunique()==num_users)

"""# Id_Canton

"""

'''Mediante la libreria uuid se implementa un ID del Canton, 
el cual va a ser único para cada dato obtenido'''

df['Id_Canton'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['Id_Canton'].nunique()==num_users)

"""# Id_Coordenada"""

'''Mediante la libreria uuid se implementa un ID a Coordenadas, 
el cual va a ser único para cada dato'''

df['Id_Coor'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['Id_Coor'].nunique()==num_users)

"""# Resultados"""

#Creacion del dataset
df.to_csv('dataset_Ciudad.csv')

#Visualizacion del dataset
pd.read_csv('dataset_Ciudad.csv', index_col=0)