# -*- coding: utf-8 -*-
"""[NRC_8393]_PROYECTO_ToapantaMartinez_JonathanElian_COORDENANDAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aYBbmjQkez2YBkSBoQ8HO0OIcMCiR40j
"""

'''Primero importamos todas las librerias 
que vamos a utilizar'''
!pip install faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

#Numero de datos a obtener
num_users = 5000

# Generar 3 atributos de la entidad Coordenandas
features = [
    "Id_Coor",
    "Latitud",
    "Longitud"
]# Se crea un df para estos atributos
df = pd.DataFrame(columns=features)

"""# ID Coordenadas"""

'''Mediante la libreria uuid se implementa un ID a Coordenadas, 
el cual va a ser único para cada dato'''

df['Id_Coor'] = [uuid.uuid4().hex for i in range(num_users)]
print(df['Id_Coor'].nunique()==num_users)

"""# Latitud"""

'''En base  a nuestro problema, 
la Latitud estan asignadas a la direccion del sector que vamos a trabajar, 
provincia de pichicncha, ciudad quito, sector centro (Basadas en WGS 84)'''

df['Latitud']= [random.uniform(-0,0.9)for i in range(num_users)]

"""#Longitud"""

'''En base  a nuestro problema, 
la longitud estan asignadas a la direccion del sector que vamos a trabajar, 
provincia de pichicncha, ciudad quito, sector centro (Basadas en WGS 84)'''

df['Longitud']= [random.uniform(-79,-78)for i in range(num_users)]

"""# Resultados"""

#Creacion del dataset
df.to_csv('dataset_Coord.csv')

#Visualizacion del dataset
pd.read_csv('dataset_Coord.csv', index_col=0)